-- Séries + doneAt sur les actions récurrentes
ALTER TABLE "Action" ADD COLUMN IF NOT EXISTS "doneAt" TIMESTAMP(3);
ALTER TABLE "Action" ADD COLUMN IF NOT EXISTS "streakCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Action" ADD COLUMN IF NOT EXISTS "bestStreak" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Action" ADD COLUMN IF NOT EXISTS "lastStreakPeriod" TEXT;
