import { StyleSheet } from "react-native";

/** Styles partagés entre les écrans d’accueil Listes et Courses. */
export const listHubStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: "#F9FAFB" },
  container: { flex: 1, backgroundColor: "#F9FAFB" },
  content: { padding: 16, paddingBottom: 40 },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  headerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  screenTitle: { fontSize: 24, fontWeight: "700", color: "#111827" },
  signOut: { fontSize: 13, color: "#6B7280" },
  section: { marginBottom: 20 },
  sectionTitle: { fontSize: 15, fontWeight: "600", color: "#111827", marginBottom: 8 },
  count: { fontWeight: "400", color: "#9CA3AF" },
  empty: { fontSize: 13, color: "#9CA3AF", fontStyle: "italic" },
  createRow: { flexDirection: "row", gap: 8 },
  input: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#D1D5DB",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    backgroundColor: "#fff",
    color: "#111827",
  },
  createBtn: {
    backgroundColor: "#111827",
    borderRadius: 8,
    paddingHorizontal: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  createBtnText: { color: "#fff", fontSize: 20, fontWeight: "600" },
  listCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginBottom: 8,
  },
  listMain: { flex: 1 },
  listTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 6,
  },
  listTitle: { fontSize: 14, fontWeight: "500", color: "#111827" },
  sharedBadge: {
    fontSize: 11,
    fontWeight: "600",
    color: "#1D4ED8",
    backgroundColor: "#EFF6FF",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    overflow: "hidden",
  },
  listMeta: { fontSize: 12, color: "#9CA3AF", marginTop: 2 },
  listActions: { flexDirection: "row", gap: 12, marginLeft: 8 },
  actionBtnGreen: { fontSize: 16, color: "#16A34A" },
  actionBtnGray: { fontSize: 16, color: "#6B7280" },
  actionBtnRed: { fontSize: 14, color: "#DC2626" },
  collapseHeader: { marginBottom: 8 },
});
