import { StyleSheet } from "react-native";
import type { AppPalette } from "@/lib/theme-palette";

/** Styles partagés entre les écrans d’accueil Listes et Courses. */
export function getListHubStyles(palette: AppPalette) {
  return StyleSheet.create({
  safe: { flex: 1, backgroundColor: palette.bg },
  container: { flex: 1, backgroundColor: palette.bg },
  content: { padding: 16, paddingBottom: 40 },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  headerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  screenTitle: { fontSize: 24, fontWeight: "700", color: palette.text },
  signOut: { fontSize: 13, color: palette.textMuted },
  section: { marginBottom: 20 },
  sectionTitle: { fontSize: 15, fontWeight: "600", color: palette.text, marginBottom: 8 },
  count: { fontWeight: "400", color: palette.textSubtle },
  empty: { fontSize: 13, color: palette.textSubtle, fontStyle: "italic" },
  createRow: { flexDirection: "row", gap: 8 },
  input: {
    flex: 1,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    backgroundColor: palette.bgElevated,
    color: palette.text,
  },
  createBtn: {
    backgroundColor: palette.primary,
    borderRadius: 8,
    paddingHorizontal: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  createBtnText: { color: palette.onPrimary, fontSize: 20, fontWeight: "600" },
  listCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: palette.bgElevated,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: palette.borderSoft,
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginBottom: 8,
  },
  listMain: { flex: 1 },
  listTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 6,
  },
  listTitle: { fontSize: 14, fontWeight: "500", color: palette.text },
  sharedBadge: {
    fontSize: 11,
    fontWeight: "600",
    color: palette.badgeText,
    backgroundColor: palette.badgeBg,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    overflow: "hidden",
  },
  listMeta: { fontSize: 12, color: palette.textSubtle, marginTop: 2 },
  listActions: { flexDirection: "row", gap: 12, marginLeft: 8 },
  actionBtnGreen: { fontSize: 16, color: palette.primary },
  actionBtnGray: { fontSize: 16, color: palette.textMuted },
  actionBtnRed: { fontSize: 14, color: palette.danger },
  collapseHeader: { marginBottom: 8 },
});
}
